version: "3.9"
services:
  nextapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://10.10.53.58:3002/api/v1